## About the pRoject 

**Greetings**, this is my page for the course "*Introduction to open data science, 5 ECTS*". I found this course by a strong recommendation from my friend. I have 2 years of experience with `R`, but now want to take it to the next level with `Git`. I'm thrilled to learn proper version control and use of Github which promotes sharing/publishing code and perhaps networking with other R coders. Alongside these hopes, I anticipate loads of fun from this course! 

Lastly, check out my [GitHub repository](https://github.com/petrusk4/IODS-project). 

Let's enjoy this interesting course!

```{r echo=FALSE, fig.height=1.5, fig.width=3, message=FALSE}
pacman::p_load(tidyverse)

MyName <- "Petrus"
MyLetters <- base::strsplit(MyName, "") %>% unlist()

p <- data.frame(
  height = jitter(rep(1, times = length(MyLetters)), amount = .3),
  number = 1:length(MyLetters),
  letter = MyLetters
) %>% ggplot(aes(x = number, y = height, color = factor(number)))
p <- p + geom_text(aes(label = letter), size = 10, fontface = "bold")
# p <- p + ggdark::dark_mode(ggthemes::theme_fivethirtyeight())
p <- p + theme(legend.position = "none", strip.text = element_text(hjust = 0))
p <- p + harrypotter::scale_color_hp_d("LunaLovegood")
p <- p + xlab("") + ylab("") + coord_cartesian(ylim = c(0, 2))
p <- p + labs(caption = "4th November, 2023")
p <- p + facet_wrap(. ~ "Sincerely, ")
p

```


# 1: Start me up!

### `R` for Health Data Science book

[This book](https://argoshare.is.ed.ac.uk/healthyr_book/) is a blast to read on the couch from iPad. 

### The Exercise Set 1

I completed the chapters 1--5 and was familiar with the substance, but there were some nifty functions that I'll probably try out soon.