---
title: "IODS course project"
author: "Petrus Nuotio"
date: "`r Sys.Date()`"
# output:
#   rmdformats::robobook:
#     embed-resources: standalone
#     thumbnails: true
#     lightbox: true
#     gallery: true
#     code_folding: hide
output:
  rmdformats::downcute:
    downcute_theme: "chaos"
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: tango
    code_folding: hide
---

<!-- *** -->

# Introduction to Open Data Science - Course Project

```{r include=FALSE}
# Packages
pacman::p_load(tidyverse)

# Theme for all figs
backg <- "#141415"
ggdark::dark_theme_gray() %+replace% 
  ggplot2::theme(
    plot.background = element_rect(color = backg, fill = backg),
    legend.box.background = element_rect(fill = backg, color = backg),
    legend.background = element_rect(fill = backg, color = backg),
    panel.grid = element_line(color = "gray20")
  ) %>%
  ggplot2::theme_set()
```

```{r child = "chapter1.Rmd"}
```

```{r child = "chapter2.Rmd"}
```
